name: LabyModSK
version: ${project.version}
main: dk.superawesome.labymodsk.LabyModSK
api-version: 1.16
depend: [Skript, LabyApi]
softdepend: [Citizens]
commands:
  labymodsk:
    description: "Labymod kommand til at spawn npc"
    usage: /labymod